PS-1_prestashop - added files for tests
Katherina111/PrestaShop pull request #1
Opened 2023-04-27 08:36 UTC by Katherina111

2023-04-27 11:08 UTC, testershmester requested changes
я оставила пару комментариев в конкретных тестах. эти комментарии справедливы для всех тестов. в самих тестах нужно больше конкретных проверок. проверка на открытие страницы больше для того, чтобы убедиться, что со страницей дальше можно работать.
в остальном - продолжайте)

2023-04-27 11:08 UTC, testershmester commented on src/main/java/by/teachmeskills/page/Authentication.java
> +public class Authentication extends BasePage {
AuthenticationPage?

2023-04-27 11:08 UTC, testershmester commented on src/main/java/by/teachmeskills/page/Authentication.java
> +    public Authentication goToSinInPage() {
sign

2023-04-27 11:08 UTC, testershmester commented on src/main/java/by/teachmeskills/page/Authentication.java
> +    public PersonalPage createAnAccountPersonalInformation(String firstlName, String lastName, String passwordName) {
firstName

2023-04-27 11:08 UTC, testershmester commented on src/main/java/by/teachmeskills/page/BasePage.java
> +    protected static WebDriver driver;
если нет обоснованной необходимости, то static не нужен

2023-04-27 11:08 UTC, testershmester commented on src/test/java/by/teachmeskills/AuthenticationStepEmailTest.java
> +        new Authentication(driver).open()
Authentication authentication = new Authentication(driver);

можно создать переменную один раз и дальше ее переиспользовать

2023-04-27 11:08 UTC, testershmester commented on src/test/java/by/teachmeskills/CartPageTest.java
> +        Assert.assertTrue(new CartPage(driver).isOpened(), "The product is not added.");
здесь проверяется открытие страницы, но не наличие товара в корзине?

2023-04-27 11:08 UTC, testershmester commented on src/test/java/by/teachmeskills/CheckoutTest.java
> +        new CartPage(driver).isDisplayedPicture();
1.  new CartPage(driver) - создать переменную и переиспользовать
2. isDisplayedDescription(); и такие же штуки должны быть помещены в асерты в тестах

2023-04-27 11:08 UTC, testershmester commented on src/test/java/by/teachmeskills/PersonalPageTest.java
> +        new PersonalPage(driver).getPersonalPage().checkIsDisplayedOrderHistoryAndDetails();
все методы check это должны быть асерты в тестах. на страницах у нас размещены методы работы со страницей.
например, метод checkIsDisplayedMyAddresses может быть сделан как getMyAddresses 


`    public WebElement getMyAddresses() {
        wait.until(ExpectedConditions.visibilityOfElementLocated(MY_ADDRESSES));
        return driver.findElement(MY_ADDRESSES);
    }`

` PersonalPage personalPage = new PersonalPage(driver);
        WebElement myAddresses = personalPage.getMyAddresses();
        Assert.assertTrue(myAddresses.isDisplayed(), "My address should be displayed on the page");
        Assert.assertEquals(myAddresses.getText(), "blabla", "My address should be correct");
        `

2023-05-02 05:41 UTC, Katherina111 commented on src/main/java/by/teachmeskills/page/Authentication.java
> +public class Authentication extends BasePage {
changed

2023-05-02 05:44 UTC, Katherina111 commented on src/main/java/by/teachmeskills/page/Authentication.java
> +    public Authentication goToSinInPage() {
changed

2023-05-02 05:45 UTC, Katherina111 commented on src/main/java/by/teachmeskills/page/Authentication.java
> +    public PersonalPage createAnAccountPersonalInformation(String firstlName, String lastName, String passwordName) {
changed

2023-05-02 05:46 UTC, Katherina111 commented on src/main/java/by/teachmeskills/page/BasePage.java
> +    protected static WebDriver driver;
исправлено

2023-05-02 05:50 UTC, Katherina111 commented on src/test/java/by/teachmeskills/AuthenticationStepEmailTest.java
> +        new Authentication(driver).open()
исправлено

2023-05-02 06:26 UTC, Katherina111 commented on src/main/java/by/teachmeskills/page/BasePage.java
> +    protected static WebDriver driver;
в тестах есть необходимость, поэтому оставила

2023-05-02 07:07 UTC, Katherina111 commented on src/test/java/by/teachmeskills/CartPageTest.java
> +        Assert.assertTrue(new CartPage(driver).isOpened(), "The product is not added.");
да, этот тест, только открывает страницу, и не проверяет наличие товара в корзине
спасибо, исправила тест

2023-05-02 07:30 UTC, Katherina111 commented on src/test/java/by/teachmeskills/CheckoutTest.java
> +        new CartPage(driver).isDisplayedPicture();
исправлено

2023-05-02 08:47 UTC, Katherina111 commented on src/test/java/by/teachmeskills/PersonalPageTest.java
> +        new PersonalPage(driver).getPersonalPage().checkIsDisplayedOrderHistoryAndDetails();
исправлено

2023-05-03 13:42 UTC, merged